export const allEvents = [
  'Paper Presentation',
  'Poster Presentation',
  'Circuitrix',
  'Coding Contest',
  'Web Designing',
  'Technical Quiz',
  'Project Expo',
  'Elocution',
  'Picture Connect',
  'Singing',
  'Dancing',
  'Antyakshari',
  'Dumb Charades',
  'General Quiz',
  'Fancy Dress',
];
export const participantLimits = {
  'Project Expo': 3,
  'Technical Quiz': 2,
  'Paper Presentation': 1,
  'Poster Presentation': 1,
  'Coding Contest': 1,
  'Web Designing': 1,
  Circuitrix: 0,
  Elocution: 0,
  'Picture Connect': 2,
  Singing: 0,
  Dancing: 4,
  Antyakshari: 3,
  'Dumb Charades': 3,
  'General Quiz': 2,
  'Fancy Dress': 0,
};
